version: "3.8"

services:
  backend:
    build:
      context: ./back-end # Chỉ thẳng vào thư mục code back-end trên máy bạn
    ports:
      - "3637:3636"
    volumes:
      - ./back-end:/app # Giúp bạn sửa code đến đâu, Docker cập nhật đến đó
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend # Chỉ thẳng vào thư mục code frontend trên máy bạn
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
