# back-end a
name: Deploy Backend

on:
  push:
    branches:
      - deploy-backup
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      ai: ${{ steps.filter.outputs.ai }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'back-end/**'

            ai:
              - 'ai-services/**'

  deploy:
    needs: changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PORT: ${{ secrets.PORT }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          OCR_SERVICE_URL: ${{ secrets.OCR_SERVICE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          VNPT_ACCESS_TOKEN: ${{ secrets.VNPT_ACCESS_TOKEN }}
          VNPT_EKYC_URL: ${{ secrets.VNPT_EKYC_URL }}
          VNPT_TOKEN_ID: ${{ secrets.VNPT_TOKEN_ID }}
          VNPT_TOKEN_KEY: ${{ secrets.VNPT_TOKEN_KEY }}
          VNP_HASH_SECRET: ${{ secrets.VNP_HASH_SECRET }}
          VNP_IPN_URL: ${{ secrets.VNP_IPN_URL }}
          VNP_RETURN_URL: ${{ secrets.VNP_RETURN_URL }}
          VNP_TMN_CODE: ${{ secrets.VNP_TMN_CODE }}
          VNP_URL: ${{ secrets.VNP_URL }}
          VNPT_DOMAIN: ${{ secrets.VNPT_DOMAIN }}
          VNPAY_HOST: ${{ secrets.VNPAY_HOST}}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

          envs: SUPABASE_URL,SUPABASE_ANON_KEY,SUPABASE_SERVICE_ROLE_KEY,PORT,MAIL_FROM,OCR_SERVICE_URL,RESEND_API_KEY,VNPT_ACCESS_TOKEN,VNPT_EKYC_URL,VNPT_TOKEN_ID,VNPT_TOKEN_KEY,VNP_HASH_SECRET,VNP_IPN_URL,VNP_RETURN_URL,VNP_TMN_CODE,VNP_URL,FRONTEND_URL

          script: |
            ~/deploy.sh